#! /usr/bin/env sh

# MacOS
if [ "${OS}" = "Darwin" ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ -x $(command -v brew) ]; then
    brew bundle --file=~/.local/packages/Brewfile
fi

# Debian-like
if [ -x $(command -v apt) ]; then
    apt update && apt install -y $(sed -e '/\s*#.*/d' /root/.local/packages/apt.txt)
fi

# Alpine
if [ -x $(command -v apk) ]; then
    # TODO: Add Alpine packages
    apk update
fi

# Anything with Python
if [ -x $(command -v pip) ]; then
    pip install -r ~/.local/packages/pip.txt
fi

# Setup ZSH / Prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git ${HOME}/.config/zsh/.zprezto
zsh ${HOME}/.yadm/bin/prezto.zsh || true

# Install YADM
git clone https://github.com/TheLocehiliosan/yadm.git /opt/yadm
ln -s /opt/yadm/yadm /usr/local/bin/yadm
