#! /usr/bin/env sh

# This script assumes the pre-installation of curl and sed


# MacOS
if [ "$(uname -s)" = "Darwin" ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if command -v brew >/dev/null 2>&1; then
    brew bundle --file=${HOME}/.local/packages/Brewfile
fi

install_ripgrep() {
    RIPGREP=ripgrep-0.7.1-x86_64-unknown-linux-musl
    RIPGREP_OPT=${HOME}/.local/opt/ripgrep
    mkdir -p ${RIPGREP_OPT}
    curl -fsSL https://github.com/BurntSushi/ripgrep/releases/download/0.7.1/${RIPGREP}.tar.gz | tar xzC ${RIPGREP_OPT} --strip-components=1 ${RIPGREP}
    ln -s ${RIPGREP_OPT}/rg ${HOME}/.local/bin/rg
    mkdir -p ${HOME}/.local/share/man/man1
    ln -s ${RIPGREP_OPT}/rg.1 ${HOME}/.local/share/man/man1/rg.1
    mandb
}

# Debian-like
if command -v apt >/dev/null 2>&1; then
    sudo apt update && sudo apt install -y $(sed -e '/\s*#.*/d' ${HOME}/.local/packages/apt.txt)
    install_ripgrep
fi


# Alpine
if command -v apk >/dev/null 2>&1; then
    apk add --no-cache $(sed -e '/\s*#.*/d' ${HOME}/.local/packages/apk.txt)
    install_ripgrep
fi


# Anything with Python
if command -v python3.6 >/dev/null 2>&1; then
    ln -s /usr/bin/python3.6 /usr/bin/python3
fi

if command -v python3 >/dev/null 2>&1; then
    ln -s /usr/bin/python3 /usr/bin/python
fi

if command -v python >/dev/null 2>&1; then
    curl -fsSL https://bootstrap.pypa.io/get-pip.py | python
    python -m pip install --upgrade --force-reinstall pip
    pip install -r ${HOME}/.local/packages/pip.txt
fi


# Initialize Vim plugins
if command -v vim >/dev/null 2>&1; then
  vim +PlugUpdate +PlugClean! +qall
fi


# Setup ZSH / Prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git ${HOME}/.config/zsh/.zprezto
zsh ${HOME}/.yadm/bin/prezto.zsh || true
chsh -s $(which zsh)

# Maybe I shouldn't be doing this one...
# rm -f ${HOME}/.bashrc && rm -f ${HOME}/.profile && -f ${HOME}/.bash_profile


# Install YADM
git clone https://github.com/TheLocehiliosan/yadm.git ${HOME}/.local/opt/yadm
ln -s ${HOME}/.local/opt/yadm/yadm ${HOME}/.local/bin/yadm
${HOME}/.local/bin/yadm alt
